FROM ubuntu:20.04
LABEL maintainer "Al S xee5ch.gh.al@ila5.info"

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
	software-properties-common

RUN add-apt-repository ppa:inkscape.dev/stable && \
	apt-get update && apt-get install -y \
	inkscape \
	--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

VOLUME /workspace
WORKDIR /workspace

ENTRYPOINT [ "inkscape" ]